spring:
  application:
    name: credit-suise-file-based-log-analyzer
  datasource:
    driver-class-name: org.hsqldb.jdbc.JDBCDriver
    url: jdbc:hsqldb:file:db/alertsdb;DB_CLOSE_DELAY=1000
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update

app:
  log-analyser:
    alert-threshold-ms: 4
    table-rows-writeoff-count: 1

server:
  port: 8080 # default port. can be ignorned